### ISSUE TITLE
Running on Open source models

### ISSUE THREAD

**Issue by shubham8550** [ecriv-ai/ecrivai#7]
my plan is to run it 24/7 on my servers with some modifications 
i tried som 7b ggup /llama cpp models they do work with this but somehow stops generating
 (i suppose i did not configured langchain properly)
if i get work work effectively ill give some updates here till then 

if anyone tries something similar please post stuff so i can refer and improve:)

**Comment by shubham8550** [comment]
**i tried openhermes-2-mistral-7b and it gave good results**

sample Op:-


---
title: "How to Build a Solar Panel"
date: 2023-11-29T12:28:35+00:00
draft: false
---

# How to Build a Solar Panel
When it comes to renewable energy, solar power is one of the most popular and widely used sources. It's clean, efficient, and sustainable, making it an attractive option for households, businesses, and communities around the world.
If you're interested in harnessing the power of the sun, building a solar panel might seem like a daunting task. But with the right tools, materials, and guidance, anyone can do it. In this blog post, we'll walk you through the steps of how to build a solar panel from scratch.
## Why Build a Solar Panel?
Solar panels have many benefits, including:
- Reducing your carbon footprint by generating clean energy
- Saving money on electricity bills
- Increasing the value of your property
- Providing backup power in case of emergencies or outages
By building your own solar panel, you can also learn new skills and enjoy a sense of satisfaction and accomplishment. Plus, it's a fun and rewarding project that you can do with friends or family members.
## What You'll Need
Before we get started, let's take a look at the materials and tools you'll need to build a solar panel:
- Solar cells (monocrystalline or polycrystalline)
- Bus bar wire
- Soldering iron
- Solder
- Silicone caulk
- Vinyl gloves
- Safety goggles
- Wire stripper
- Screwdriver
- Drill
- Plywood or wood panel
- Jumper wires
- Solar charge controller
- Inverter (optional)
You can usually find these items at your local hardware store or online. Make sure to choose high-quality materials that are suitable for outdoor use, as solar panels are exposed to the elements.
## How to Build a Solar Panel
Now that you have everything you need, it's time to get started! Follow these steps to build a solar panel:
### Step 1: Prepare the Surface
Start by cutting a piece of plywood or wood panel to the desired size and shape. This will serve as the base for your solar panel. You can use a saw or a jigsaw to cut the wood, but be careful not to damage it. Once you have the right size, sand the edges smooth and clean any dust or debris.
### Step 2: Attach Solar Cells
Next, place the solar cells on the surface of the wood panel, making sure they're evenly spaced and aligned. You can use silicone caulk to attach them temporarily, but you'll need to solder them later for a more permanent bond.
### Step 3: Add Bus Bar Wire
Bus bar wire is used to connect multiple solar cells together in series or parallel circuits. Cut the bus bar wire to the desired length and use a soldering iron to attach it to the positive and negative terminals of each solar cell. Make sure the connections are tight and secure, as loose wires can cause shorts or other problems.
### Step 4: Solder Jumper Wires
Using jumper wires, connect the positive and negative terminals of each solar cell to form a series circuit. This will create a single path for electricity to flow through the solar panel. You'll need to solder the jumper wires to the bus bar wire, making sure they're tightly connected and insulated.
### Step 5: Install Solar Charge Controller
A solar charge controller is used to regulate the voltage and current of the solar panel. This helps protect your batteries from overcharging or damage. Choose a high-quality solar charge controller that matches the output of your solar panel, and follow the manufacturer's instructions for installation.
### Step 6: Attach Inverter (Optional)
If you plan to use your solar panel to power appliances or devices that require AC power, you'll need an inverter. This converts the DC voltage from the solar panel to AC voltage for use with standard outlets and plugs. Choose an inverter that matches the output of your solar panel and follow the manufacturer's instructions for installation.
### Step 7: Test Your Solar Panel
Once you've completed all the steps, it's time to test your solar panel. Connect it to a voltmeter or multimeter to check the voltage and current output. If everything looks good, you can install your solar panel on a roof or mount it on a stand. Make sure it's oriented towards the sun and securely mounted to avoid damage or theft.
## Conclusion
Building a solar panel may seem challenging at first, but with some patience and perseverance, anyone can do it. By following these steps

**Comment by ruankie** [comment]
That's very cool. I'm glad you managed to get it working! 🥳

**Comment by ruankie** [comment]
@shubham8550 I imagine this only depended on some Langchain integration once the model ran. Please feel free to share more details about how you managed to get it working if you're able.

**Comment by shubham8550** [comment]
> @shubham8550 I imagine this only depended on some Langchain integration once the model ran. Please feel free to share more details about how you managed to get it working if you're able.



i have it running on my server in infinite loop 
i also added stable diffusion XL in ur code and changed design  and some more improvements

https://blog.m0n0.site/

**Comment by shubham8550** [comment]
and seince i use  free tier server servers from oracle whole thing running with no cost for me

**Comment by shubham8550** [comment]
one thing i noticed that google hates ai generated content its not getting listed properly
